### ISSUE TITLE
Make check_hrp public

### ISSUE THREAD

**Issue by kwek20** [rust-bitcoin/rust-bech32#99]
I would like to only verify that the hrp part is valid.
The crate has a method; `check_hrp` but this is private.

I would prefer not to copy the code :) 

Thanks 🙏

**Comment by tcharding** [comment]
We can do that, no worries! Thanks for the issue.

**Comment by kwek20** [comment]
@tcharding Thank you for the work on the new type! What is your release pattern like?

**Comment by apoelstra** [comment]
@kwek20 we are in the middle of a very large refactoring of this crate. I think we'll be done by the end of June, if not sooner, but unfortunately we won't really be in a position to release intermediate crates until it is done (I think).

After that, this crate will probably return to its previous cadence of releasing only as-needed, since it's a small crate which implements pure functions and doesn't need too much upgrading.

**Comment by tcharding** [comment]
Although we should have a pre-release version out soonish.

**Comment by tcharding** [comment]
We can Close this issue now as `Hrp` code was released in the 0.10.0-alpha release.

https://docs.rs/bech32/0.10.0-alpha/bech32/primitives/hrp/struct.Hrp.html
